### ISSUE TITLE
Menus in the 18F Guides style don't expand consistantly

### ISSUE THREAD

**Issue by wslack** [18F/guides-style#18]
Paging @andrewmaier and @mbland.

Open: https://methods.18f.gov/ and https://pages.18f.gov/frontend/
Click the "+" in the side menu. Should extend menu for methods but not frontend. On frontend, menu only expands when you open that page.

All repos should behave like the Methods site.

Source code that I think controls? https://github.com/18F/methods/blob/18f-pages-staging/_config.yml and https://github.com/18F/frontend/blob/18f-pages-staging/_config.yml

**Comment by mbland** [comment]
I think there's a problem in the `guides_style_18f` template somewhere whereby jQuery doesn't always load properly. I can look into it.

**Comment by juliaelman** [comment]
The issue has to do with the `async` attribute being added to the `<script>` tag. Since the scripts are being loaded at the bottom of the page, it is not necessary to add this and is causing load issues for the scripts themselves. This then causes jQuery to not load properly, thus disabling the accordion functionality.

**Comment by juliaelman** [comment]
See reference here too: https://github.com/18F/pages/issues/53

**Comment by wslack** [comment]
Yay team! Happy to have you back Julia!
